name: Build

on: push

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        strategy:
            matrix:
                os: [windows-latest, ubuntu-22.04, macos-latest]

        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x

            - name: Use Yarn
              run: npm install yarn -g

            - name: Install dependencies (Linux)
              if: runner.os == 'Linux'
              run: |
                  sudo dpkg --add-architecture i386
                  sudo apt-get update
                  sudo apt-get install -y gcc-i686-linux-gnu libc6-dev:amd64 libc6-dev:i386 libgtk-3-dev libwebkit2gtk-4.0-dev libglib2.0-dev libssl-dev:amd64 libssl-dev:i386 libappindicator3-dev librsvg2-dev libappindicator-dev libgdk3.0-cil libatk1.0-dev

            - name: Add Rust build targets (Windows)
              if: runner.os == 'Windows'
              run: |
                  rustup target add aarch64-pc-windows-msvc
                  rustup target add i686-pc-windows-msvc
                  rustup target add x86_64-pc-windows-msvc

            - name: Add Rust build targets (Linux)
              if: runner.os == 'Linux'
              run: |
                  rustup target add i686-unknown-linux-gnu
                  rustup target add x86_64-unknown-linux-gnu

            - name: Add Rust build targets (macOS)
              if: runner.os == 'macOS'
              run: |
                  rustup target add aarch64-apple-darwin
                  rustup target add x86_64-apple-darwin

            - name: Get Yarn cache directory path (Windows)
              if: runner.os == 'Windows'
              run: echo "yarn_cache_dir=$(yarn cache dir)" >> $env:GITHUB_ENV

            - name: Get Yarn cache directory path (non-Windows)
              if: runner.os != 'Windows'
              run: echo "yarn_cache_dir=$(yarn cache dir)" >> $GITHUB_ENV

            - name: Cache Yarn dependencies
              id: yarn-cache
              uses: actions/cache@v3
              with:
                  path: ${{ env.yarn_cache_dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-

            - name: Cache Cargo dependencies
              id: cargo-cache
              uses: actions/cache@v3
              with:
                  path: |
                      ~/.cargo/bin/
                      ~/.cargo/registry/index/
                      ~/.cargo/registry/cache/
                      ~/.cargo/git/db/
                      src-tauri/target/
                  key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

            - name: Run install
              run: yarn install --prefer-offline

            - name: Build app
              if: runner.os == 'Linux'
              run: |
                  export PKG_CONFIG_SYSROOT_DIR=/
                  yarn run tauri:build

            - name: Build app
              if: runner.os != 'Linux'
              run: yarn run tauri:build

            - name: Upload dist (Windows, Setup)
              if: runner.os == 'Windows'
              uses: actions/upload-artifact@v3
              with:
                  name: win32-setup
                  path: "out/*-setup-*.exe"

            - name: Upload dist (Windows, MSI)
              if: runner.os == 'Windows'
              uses: actions/upload-artifact@v3
              with:
                  name: win32-msi
                  path: "out/*-setup-msi-*.msi"

            - name: Upload dist (Windows, Standalone)
              if: runner.os == 'Windows'
              uses: actions/upload-artifact@v3
              with:
                  name: win32-standalone
                  path: "out/*-standalone-*.exe"

            - name: Upload dist (Linux, Deb)
              if: runner.os == 'Linux'
              uses: actions/upload-artifact@v3
              with:
                  name: linux-deb
                  path: "out/*.deb"

            - name: Upload dist (Linux, AppImage)
              if: runner.os == 'Linux'
              uses: actions/upload-artifact@v3
              with:
                  name: linux-appimage
                  path: "out/*.AppImage"

            - name: Upload dist (macOS)
              if: runner.os == 'macOS'
              uses: actions/upload-artifact@v3
              with:
                  name: macos-dmg
                  path: "out/*.dmg"

            - name: Create release
              if: startsWith(github.ref, 'refs/tags/v')
              uses: softprops/action-gh-release@v1
              with:
                  files: out/*
                  generate_release_notes: true
                  append_body: false

            # - name: Download uploader
            #   uses: robinraju/release-downloader@v1.6
            #   with:
            #       repository: ${{ secrets.UPLOADER_RES_REPO }}
            #       tag: uploader
            #       fileName: upload.tar.gz

            # - name: Upload dist to server
            #   run: |
            #       mkdir upload
            #       tar -z -xf upload.tar.gz -C upload
            #       node ./upload/build/main.js "./out" "magenta-player-${{ runner.os }}" "${{ secrets.UPLOADER_SECRET }}.zip"
